#!/bin/bash
# ============================================================
# setup.sh — Aegis Infra SaaS Backend
# Automates Docker Compose startup for the full stack
# ============================================================
# Usage:
#   bash setup.sh          → Start all services (foreground)
#   bash setup.sh -d       → Start in detached/background mode
#   bash setup.sh --stop   → Stop all services
#   bash setup.sh --clean  → Stop & remove volumes (fresh DB)
# ============================================================

set -e  # Exit on any error

# ── Colours ───────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# ── Banner ────────────────────────────────────────────────
echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════╗"
echo "║         Aegis Infra — SaaS Backend           ║"
echo "║         Docker Compose Setup Script          ║"
echo "╚══════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Check Docker is running ───────────────────────────────
if ! docker info > /dev/null 2>&1; then
  echo -e "${RED}✗ Docker is not running. Please start Docker Desktop and try again.${NC}"
  exit 1
fi
echo -e "${GREEN}✓ Docker is running${NC}"

# ── Check .env file exists — auto-create if missing ──────
if [ ! -f ".env" ]; then
  echo -e "${YELLOW}⚠ .env file not found. Let's create one now...${NC}"
  echo ""

  read -p "  DB_USERNAME     [root]: " DB_USERNAME
  DB_USERNAME=${DB_USERNAME:-root}

  read -sp "  DB_PASSWORD     : " DB_PASSWORD
  echo ""

  read -p "  APP_ADMIN_PASSWORD [superadmin123]: " APP_ADMIN_PASSWORD
  APP_ADMIN_PASSWORD=${APP_ADMIN_PASSWORD:-superadmin123}

  read -p "  APP_USER_PASSWORD  [password123]: " APP_USER_PASSWORD
  APP_USER_PASSWORD=${APP_USER_PASSWORD:-password123}

  read -p "  JWT_SECRET      (64-char hex key): " JWT_SECRET

  read -p "  JWT_EXPIRATION  [86400000]: " JWT_EXPIRATION
  JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}

  read -p "  MAIL_USERNAME   (Gmail address): " MAIL_USERNAME

  read -sp "  MAIL_PASSWORD   (Gmail App Password): " MAIL_PASSWORD
  echo ""

  read -p "  GEMINI_API_KEY  : " GEMINI_API_KEY

  cat > .env <<EOF
# Auto-generated by setup.sh
DB_URL=jdbc:mysql://localhost:3306/saasdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

APP_ADMIN_PASSWORD=${APP_ADMIN_PASSWORD}
APP_USER_PASSWORD=${APP_USER_PASSWORD}

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION=${JWT_EXPIRATION}

MAIL_USERNAME=${MAIL_USERNAME}
MAIL_PASSWORD=${MAIL_PASSWORD}

GEMINI_API_KEY=${GEMINI_API_KEY}
gemini.api.key=${GEMINI_API_KEY}

SERVER_PORT=8080
SPRING_PROFILES_ACTIVE=prod
EOF

  echo -e "${GREEN}✓ .env file created successfully!${NC}"
else
  echo -e "${GREEN}✓ .env file found${NC}"
fi

# ── Handle flags ─────────────────────────────────────────
case "$1" in
  --stop)
    echo -e "${YELLOW}► Stopping all services...${NC}"
    docker compose down
    echo -e "${GREEN}✓ All services stopped.${NC}"
    exit 0
    ;;
  --clean)
    echo -e "${YELLOW}► Stopping services and removing volumes (database will be erased)...${NC}"
    docker compose down -v
    echo -e "${GREEN}✓ All services stopped and volumes removed.${NC}"
    exit 0
    ;;
  -d)
    DETACHED="-d"
    ;;
  *)
    DETACHED=""
    ;;
esac

# ── Start services ────────────────────────────────────────
echo -e "${YELLOW}► Building and starting services...${NC}"
docker compose up --build $DETACHED

# ── If detached, show status ──────────────────────────────
if [ "$DETACHED" = "-d" ]; then
  echo ""
  echo -e "${GREEN}✓ Services started in background!${NC}"
  echo -e "${CYAN}"
  echo "  App:      http://localhost:8080"
  echo "  Database: localhost:3306 (saasdb)"
  echo ""
  echo "  Logs:     docker compose logs -f app"
  echo "  Stop:     bash setup.sh --stop"
  echo -e "${NC}"
  docker compose ps
fi
