spring:
  application:
    name: saas

  datasource:
    url: jdbc:mysql://localhost:3306/saasdb
    username: root
    password: "abhi@2004"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: abhishekmohanty78962@gmail.com
    password: hrwarblvwgcjgvqk
    protocol: smtp
    default-encoding: UTF-8

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  ai:
    google:
      genai:
        api-key: AIzaSyCwTpeByfBAFaYg7CnEsBVYyBhJlYaOxv0


application:
  security:
    jwt:
      secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      expiration: 1800000
