server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: saas

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD} 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 1800000
